spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://b17537d8dd1502:e8fd0dfe@us-cdbr-east-02.cleardb.com/heroku_25999abcbbc76ce?reconnect=true
    username: b17537d8dd1502
    password: e8fd0dfe
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  devtools:
    livereload:
      enabled: true